config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/profile'
  get 'welcome/results'
  get 'welcome/favourites'
  get 'welcome/following'

  post 'properties/:id/add_to_f', to: 'properties#add_to_f', as: 'add_to_f_property'
  post 'properties/:id/remove_from_f', to: 'properties#remove_from_f', as: 'remove_from_f_property'

  post 'properties/:id/follow', to: 'properties#follow', as: 'follow'
  post 'properties/:id/unfollow', to: 'properties#unfollow', as: 'unfollow'


  get 'properties/:id/summary', to: 'properties#summary', as: 'summary'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"
  resources :properties do
    resources :prenotations

    resources :questions do
      resources :answers
    end
    
    resources :reviews
  end

  resources :conversations do
    resources :messages
  end
  resources :ratings
  resources :answer_ratings
  resources :reviews
  resources :questions
end

app/models/property.rb
class Property < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5, maximum: 50}
  validates :description, presence:true, length: { minimum: 10}
  validates :price, presence:true, numericality: {greater_than: 0}
  validates :city, presence: true

  belongs_to :user
  has_and_belongs_to_many :favouriters, class_name: "User", join_table: "favouriters_and_favourites"
  paginates_per 3

  serialize :categories, Array

  has_attached_file :img1, styles: { small: "200x200>", medium: "300x300>", thumb: "100x100>" }, default_url: ":style/default_local.jpg"
  validates_attachment_content_type :img1, content_type: /\Aimage\/.*\z/

  has_attached_file :img2, styles: { small: "200x200>", medium: "300x300>", thumb: "100x100>" }, default_url: ":style/default_local.jpg"
  validates_attachment_content_type :img2, content_type: /\Aimage\/.*\z/

  has_attached_file :img3, styles: { small: "200x200>", medium: "300x300>", thumb: "100x100>" }, default_url: ":style/default_local.jpg"
  validates_attachment_content_type :img3, content_type: /\Aimage\/.*\z/

  has_many :questions, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :prenotations, dependent: :destroy

  geocoded_by :city
  after_validation :geocode
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :authenticate_user!, except: [:show, :summary]

  def index
    @properties = current_user.properties.page params[:page]
  end

  def summary
    @property = Property.find(params[:id])
    @properties = Property.where(:user => @property.user).page params[:page]
  end

  def show
    @property = Property.find(params[:id])
    @correlated = Property.where(categories: @property.categories)
    @questions = @property.questions.order(:valutation).reverse
    media(@property)
    @prenotations = Prenotation.all
  end

  def media(property)
    @counter = 0
    @valutazione = 0
    property.reviews.each do |r|
      @valutazione = @valutazione + r.valutation
      @counter = @counter + 1
    end
    if @counter==0
      @counter=1
    end
    @valutazione = @valutazione/@counter
    if @valutazione.modulo(1)>0.5
      @valutazione = @valutazione + 1
    end
    property.valutation = @valutazione
    property.save
  end

  def add_to_f
    @property = Property.find(params[:id])
    current_user.favourites << @property
    redirect_to @property
  end

  def remove_from_f
    @property = Property.find(params[:id])
    current_user.favourites.delete(@property)
    redirect_to @property
  end

  def follow
    @property = Property.find(params[:id])
    current_user.followings << @property.user
    redirect_to @property
  end

  def unfollow
    @property = Property.find(params[:id])
    current_user.followings.delete(@property.user)
    redirect_to @property
  end

  def new
    @property = Property.new
  end

  def create
    @property = current_user.properties.build(property_params)
    if @property.save
      redirect_to @property
    else
      render 'new'
    end
  end

  def edit
    @property = Property.find(params[:id])
  end

  def update
    @property = Property.find(params[:id])
    if @property.update(property_params)
        redirect_to @property
    else
        render 'edit'
    end
  end

  def destroy
    @property = Property.find(params[:id])
    @property.destroy

    redirect_to properties_path
  end

  private def property_params
    params.require(:property).permit(:title, :description, :price, :city, :img1, :img2, :img3, :offer, :valutation, categories: [])
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_list.html.erb
<% @properties.each do |p| %>
  <hr>
    <b>Anteprima:</b>
    <br>
    <%= image_tag p.img1.url(:thumb), size: "70x50" %><br>
    <b>Titolo:</b> <%= p.title %><br>

    <% if p.offer == nil %>
    <b>Prezzo:</b> <%= p.price %>€<br>
    <% else %>
    <b>Prezzo:</b> <del><%= p.price %>€</del> <font color="red"><%= p.offer %>€ </font><br>
    <%end%>

    <b>Città:</b> <%= p.city %><br/>
    <b>Utente:</b>
    <%= p.user.username %>
    <br>

    <%= link_to "Vedi", property_path(p), :class => 'btn btn-success' %>
    <br>
<% end %>

<%= paginate @properties %>

app/views/properties/edit.html.erb
<h1>Modifica Inserzione</h1>
<%= form_for(@property) do |p| %>

  <!--ERRORI-->
  <% if @property.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <div id="error_explanation">
        <h2>
          <%= pluralize(@property.errors.count, "error") %>
        </h2>
          <ul>
          <% @property.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <p>
    <%= p.label :titolo %><br>
    <%= p.text_field :title %><br>
  </p>

  <p>
    <%= p.label :descrizione %><br>
    <%= p.text_area :description %>
  </p>

  <p>
    <%= p.label :prezzo %><br>
    <%= p.text_field :price %><br>
  </p>

  <p>
    <%= p.label :sconto %><br>
    <%= p.text_field :offer %><br>
  </p>
  <p>
    <%= p.label :città %><br>
    <%= p.text_field :city %><br>
  </p>

  <p>
    <%= p.label "Immagine 1" %><br>
    <%= p.file_field :img1 %><br>
  </p>

  <p>
    <%= p.label "Immagine 2" %><br>
    <%= p.file_field :img2 %><br>
  </p>

  <p>
    <%= p.label "Immagine 3" %><br>
    <%= p.file_field :img3 %><br>
  </p>

  <p>
    <%= p.submit "Modifica" %>
  </p>
<% end %>

app/views/properties/index.html.erb
<h1>Mie inserzioni:</h1>

<%= link_to "+ Crea inserzione +", new_property_path, :class => 'btn btn-primary'%><p/>

<p/><%= render 'list' %>

app/views/properties/new.html.erb
<h1>Crea Inserzione</h1>
<%= form_for :property, url: properties_path do |p| %>

  <!--ERRORI-->
  <% if @property.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <div id="error_explanation">
        <h2>
          <%= pluralize(@property.errors.count, "error") %>
        </h2>
          <ul>
          <% @property.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>


  <p class="field">
    <%= p.label :titolo %><br>
    <%= p.text_field :title, id: :Titolo,:size=> 30 %><br>
  </p>

  <p >
    <%= p.label :descrizione %><br>
    <%= p.text_area :description, id: :Descrizione, :size=> 30 %>
  </p>

  <p class="field">
    <%= p.label :prezzo %><br>
    <%= p.text_field :price, id: :Prezzo, :size=> 30  %><br>
  </p>

  <p class="field" >
    <%= p.label :città %><br>
    <%= p.text_field :city, id: :address_city, :size=> 30, :placeholder=> "Inserisci la città" %><br>
  </p>


  <p>
    <%= p.label "Immagine 1" %><br>
    <%= p.file_field :img1 %><br>
  </p>

  <p>
    <%= p.label "Immagine 2" %><br>
    <%= p.file_field :img2 %><br>
  </p>

  <p>
    <%= p.label "Immagine 3" %><br>
    <%= p.file_field :img3 %><br>
  </p>

  <hr>
  <h3> Sezione categorie </h3>
  <table class='correlated'>
    <tr><th><%= p.label("Tipologia di acquisto") %></th></tr>
    <tr><th><%= p.select :categories, [ ["Affitto", "Affitto"], ["Prenotazione", "Prenotazione"] ], {:include_blank => false}, {:multiple => true}%></th></tr>
  </table>
  <table class='correlated'>
    <tr><th><%= p.label("Tipologia di proprietà") %></th></tr>
    <tr><th><%= p.select :categories, [ ["Abitazione", "Abitazione"], ["B&B", "B&B"], ["Casa Vacanza", "Casa Vacanza"], ["Attività Commerciale", "Attività Commerciale"] ], {:include_blank => false}, {:multiple => true}%></th></tr>
  </table>
  <table class='correlated'>
    <tr><th><%= p.label("Preferenza fascia oraria") %></th></tr>
    <tr><th><%= p.select :categories, [ ["Mattina", "Mattina"], ["Pomeriggio", "Pomeriggio"], ["Sera", "Sera"], ["Più Giorni", "Più Giorni"] ], {:include_blank => false}, {:multiple => true}%></th></tr>
  </table>
  <table class='correlated'>
    <tr><th><%= p.label("Preferenza stanza") %></th></tr>
    <tr><th><%= p.select :categories, [ ["Intera Casa", "Intera Casa"], ["Stanza Condivisa", "Stanza Condivisa"], ["Stanza Privata", "Stanza Privata"] ], {:include_blank => false}, {:multiple => true}%></th></tr>
  </table>

  <br><br><br><br><br><br><hr>
  <p>
    <%= p.submit "Crea Inserzione", :class => "btn btn-primary" %>
  </p>
<% end %>
<script>


  function initAutocomplete() {


    // Create the search box and link it to the UI element.
    var input = document.getElementById('address_city');
    var searchBox = new google.maps.places.SearchBox(input);
    map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

    // Bias the SearchBox results towards current map's viewport.
    map.addListener('bounds_changed', function() {
      searchBox.setBounds(map.getBounds());
    });

    // Listen for the event fired when the user selects a prediction and retrieve
    // more details for that place.
    searchBox.addListener('places_changed', function() {
      var places = searchBox.getPlaces();

      if (places.length == 0) {
        return;
      }


    });
  }

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCQIh8MGEehUptz2u7vr8JbRvyvB6mA4M8&libraries=places&callback=initAutocomplete"
     async defer></script>

app/views/properties/show.html.erb
<script>
  var set_stars = function(form_id, stars) {
    for (i=1; i<=5; i++) {
      if(i <= stars) {
        $('#' + form_id + '_' + i).addClass('on');
      }
      else {
        $('#' + form_id + '_' + i).removeClass('on');
      }
    }
  }

  $(function() {
    $('.rating_star').click(function() {
      var star = $(this);
      var form_id = $(this).attr('data-form-id');
      var stars = $(this).attr('data-stars');
      set_stars(form_id,stars);

      $('#' + form_id + '_stars').val(stars);

      $.ajax({
        type: "post",
        url: $('#' + form_id).attr('action'),
        data: $('#' + form_id).serialize()
      });
    });
  });
</script>

<div class="page-header">
  <h1><%= @property.title %></h1>
</div>

<div class="panel panel-default">
  <div class="panel-heading"><b>Descrizione</b></div>
  <div class="panel-body">
    <div><%= @property.description %></div>
  </div>
</div>

<div class='property_images'>
  <%= image_tag @property.img1.url(:medium), size: "260x200" %>

  <%= image_tag @property.img2.url(:medium), size: "260x200" %>

  <%= image_tag @property.img3.url(:medium), size: "260x200" %>
</div>

<% if @property.offer == nil %>
<h3><p><b>Prezzo: <%= @property.price %>€</b></p></h3>
<%else %>
<h3><b><del><%= @property.price %>€</del></b> <font style="color:red"><b><%= @property.offer %>€</b></font></h3>
<%end%>

<ul class='rating'>
  <% (1..5).each do |i| %>
    <% if i <= @property.valutation %>
      <li class="rating_star_review on"></li>
    <% else %>
      <li class="rating_star_review"></li>
    <% end %>
  <% end %>
</ul>

<br><br>

<p><b>Città: </b><%= @property.city %></p>

<p>
  <b>Categorie:</b>
  | <% @property.categories.each do |c| %>
    <% if c != "" %>
      <%= c %> |
    <% end %>
  <% end %>
</p>

<p><b>Inserzione di:</b>
<%= @property.user.username %>

(<%= link_to "Vedi altro dall'utente", summary_path(@property), method: :get %>)
</p>

<% if current_user != @property.user %>
  <p><%= mail_to @property.user.email, "Vuoi prenotare? Contatta l'utente", subject: @property.title, class: 'btn btn-info' %></p>
<% end %>
<hr>

<% if current_user %>
  <p><% if @property.user == current_user || current_user.admin %>
  	<%= link_to "Modifica", edit_property_path(@property), :class => 'btn btn-warning' %>
	  <%= link_to "Elimina", property_path(@property),
		  	method: :delete,
		          data: {confirm: 'Are you sure?'},
			  :class => 'btn btn-danger' %>
  <% end %></p>
<% end %>

<% if current_user && current_user != @property.user %>
  <% if current_user.followings.exists?(@property.user.id) %>
    <%= link_to "Unfollow utente", unfollow_path(@property), method: :post, class: 'btn btn-warning' %><p/>
  <% else %>
    <%= link_to "Follow utente", follow_path(@property), method: :post, class: 'btn btn-default' %><p/>
  <% end %>
<% end %>

<br>

<% if current_user && current_user != @property.user %>
	<% if current_user.favourites.exists?(@property.id) %>
		<%= link_to "Rimuovi dai preferiti", remove_from_f_property_path(@property), method: :post, class: 'btn btn-warning' %><p/>
	<% else %>
		<%= link_to "Aggiungi ai preferiti", add_to_f_property_path(@property), method: :post, class: 'btn btn-default' %><p/>
	<% end %>
<% end %>

<p><a class="twitter-share-button"
  href="https://twitter.com/share"
  data-size="large"
  data-text="Guarda questo locale: "
  data-url="https://dev.twitter.com/web/tweet-button"
  data-hashtags="example,demo"
  data-via="twitterdev"
  data-related="twitterapi,twitter">
  <img src="http://tweetforprofits.com/UltraVid/images/share-twitter.png" style="width:210px;height:45px;">
</a></p><hr>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-6">
      <h4>Mappa:</h4>
      <p>
      <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=15&size=500x350&maptype=roadmap
      &markers=color:red%8Clabel:S%7C#{@property.latitude},#{@property.longitude}
      &key=AIzaSyB4bGTS4lIxDUcOJC8YZM3eAuyg-4JYPfQ "%>
      </p>
      <hr>
      <p>
        <h4>Proprietà nelle vicinanze:</h4>
        <% for p in @property.nearbys(10) %>
        <li>
          <%= link_to p.title, p %>, in  <%= p.city %> (<%= p.distance.round(2)%> km)
        </li>
        <% end %>
      </p>
    </div>
  </div>
</div>

<hr>

<p>
  <h4><b>Disponibilità:</b></h4>
  <br>
  <%= month_calendar events: @property.prenotations do |date, prenotations| %>
    <%= date.day %>
    <% prenotations.each do |prenotation| %>
      <div>
        <p style="color:red;">Riservato</p>
      </div>
    <% end %>
  <% end %>

  <% if current_user && (@property.user == current_user || current_user.admin) %>
    <%= link_to "Modifica disponibilità", property_prenotations_path(@property), :class => 'btn btn-warning' %>
  <% end %>
</p><hr>

<!-- ##########RECENSIONI########## -->

<div class='ratings'>
  <div class="panel panel-default">
  <div class="panel-heading"><b>Recensioni</b></div>
  <div class="panel-body">

      <% if @property.reviews.first == nil %>
      <div class="alert alert-warning" role="alert">
        <h5> Non è ancora stata scritta alcuna recensione!</h5>
      </div>
      <% else %>
        <% @property.reviews.each do |review| %>
          <div class="panel panel-default">
          <div class="panel-body">
            <p>
              <h4><%= review.user.username %></h4>
              <% if review.user.provider == nil %>
                <%= image_tag review.user.avatar.url(:thumb) %>
              <% else %>
                <%= image_tag review.user.image %>
              <% end %>              <br>
              <b>Titolo: </b> <%= review.title %><br>
              <b>Descrizione:</b>
              <p><%= review.body %></p>
              <b>Valutazione:</b>
              <ul class='rating'>
                <% (1..5).each do |i| %>
                  <% if i <= review.valutation %>
                    <li class="rating_star_review on"></li>
                  <% else %>
                    <li class="rating_star_review"></li>
                  <% end %>
                <% end %>
              </ul>
            </p><br>
            <% if current_user && (current_user == review.user || current_user.admin) %>
                <%= link_to 'Elimina', [review.property, review],
                      method: :delete,
                      data: { confirm: 'Sei sicuro?' }, :class => 'btn btn-danger' %>
            <% end %>
          </div>
          </div>
        <% end %>
      <% end %><br>

      <% if current_user && current_user != @property.user %>
        <%= link_to "Scrivi una recensione", new_review_path(:property => @property), :class => 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

<!-- ##########DOMANDE########## -->

<div class='question'>
  <div class="panel panel-default">
  <div class="panel-heading"><b>Domande</b></div>
  <div class="panel-body" >

      <% if @property.questions.first == nil %>
        <div class="alert alert-warning" role="alert">
          <h5> Non è ancora stata fatta alcuna domanda!</h5>
        </div>
      <% else %>
        <ul class='list_question'>
          <% @questions.each do |question| %>
            <div class="panel panel-default">
            <div class="panel-body">

                <b><%= question.user.username %></b>
                <br>
                <%= question.body %><br>
                <br>
                Punteggio:
                <%= question.valutation %>
                <br>
                <% if current_user %>
                  <% if question.user != current_user %>
                    <ul class='rating'>
                      <% form_id = "question_#{question.id}_rating" %>
                      <%= form_for question.ratings.last || question.ratings.build, :html => {:id => "question_#{question.id}_rating" } do |f| %>
                        <%= f.hidden_field :question_id %>
                        <%= f.hidden_field :stars, :id => "#{form_id}_stars" %>
                      <% end %>

                      <% stars = 0 %>
                      <% question.ratings.each do |r| %>
                        <% if current_user.ratings.find_by(:id => r.id) %>
                          <% stars = r.stars %>
                          <% break %>
                        <% end %>
                      <% end %>

                      <% (1..5).each do |i| %>
                        <% if i <= stars %>
                          <li class="rating_star on" data-stars="<%= i %>" data-form-id = "<%= form_id %>" id= "<%= "#{form_id}_#{i}" %>"></li>
                        <% else %>
                          <li class="rating_star" data-stars="<%= i %>" data-form-id = "<%= form_id %>" id= "<%= "#{form_id}_#{i}" %>"></li>
                        <% end %>
                      <% end %>
                    </ul><br>
                  <% end %>
                <% end %>
                <br>
                <%= link_to 'Vedi risposte', property_question_path(question), :class => 'btn btn-default' %>
                <% if current_user %>
                  <% if current_user == question.user || current_user.admin %>
                    <%= link_to 'Elimina', [question.property, question],
                               method: :delete,
                               data: { confirm: 'Sei sicuro?' }, :class => 'btn btn-danger' %>
                  <% end %>
                <% end %>

            </div>
            </div>
          <% end %>
        </ul>
      <% end %>

      <% if current_user && current_user != @property.user %>
        <%= link_to "Fai una domanda", new_question_path(:property => @property), :class => 'btn btn-primary' %>
      <% end %>
    </div>

  </div>
</div>

<br class='clear'>

<hr>
  <h4><b>Proprietà Correlate:</b></h4>
  <% @correlated.each do |p| %>
    <table class='correlated'>
      <% if p.id != @property.id %>
        <tr><th><%= image_tag(p.img1.url(:thumb), size: "90x80") %></th></tr>
        <tr><th><b>Titolo: <%= p.title %></b></th></tr>
        <% if p.offer == nil %>
          <tr><th><%= p.price %>€</th></tr>
        <% else %>
          <tr><th><del><%= p.price %>€</del> <font color="red"> <%= p.offer %>€</font></th></tr>
        <% end %>
        <tr><th><%= link_to "Vedi", property_path(p), class: 'btn btn-primary' %></th></tr>
      <% end %>
    </table>
  <% end %>
<br class='clear'>

app/views/properties/summary.html.erb
<h1>Inserzioni dell'utente:
<%= @property.user.username %></p>
</h1>

<%= render 'list' %>