config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/profile'
  get 'welcome/results'
  get 'welcome/favourites'
  get 'welcome/following'

  post 'properties/:id/add_to_f', to: 'properties#add_to_f', as: 'add_to_f_property'
  post 'properties/:id/remove_from_f', to: 'properties#remove_from_f', as: 'remove_from_f_property'

  post 'properties/:id/follow', to: 'properties#follow', as: 'follow'
  post 'properties/:id/unfollow', to: 'properties#unfollow', as: 'unfollow'


  get 'properties/:id/summary', to: 'properties#summary', as: 'summary'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"
  resources :properties do
    resources :prenotations

    resources :questions do
      resources :answers
    end
    
    resources :reviews
  end

  resources :conversations do
    resources :messages
  end
  resources :ratings
  resources :answer_ratings
  resources :reviews
  resources :questions
end

app/models/prenotation.rb
class Prenotation < ApplicationRecord
  belongs_to :property
end

app/controllers/prenotations_controller.rb
class PrenotationsController < ApplicationController
  before_action :set_prenotation, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /prenotations
  # GET /prenotations.json
  def index
    @property = Property.find(params[:property_id])
    @prenotations = @property.prenotations
  end

  # GET /prenotations/new
  def new
    @property = Property.find(params[:property_id])
    @prenotation = Prenotation.new
  end

  # POST /prenotations
  # POST /prenotations.json
  def create
    @property = Property.find(params[:property_id])
    @prenotation = @property.prenotations.create(prenotation_params)

    respond_to do |format|
      if @prenotation.save
        format.html { redirect_to property_prenotations_path(@property), notice: 'Prenotazione effettuata con successo.' }
        format.json { render :show, status: :created, location: @prenotation }
      else
        format.html { render :new }
        format.json { render json: @prenotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prenotations/1
  # DELETE /prenotations/1.json
  def destroy
    @property = Property.find(params[:property_id])
    @prenotation.destroy
    respond_to do |format|
      format.html { redirect_to property_prenotations_path(@property), notice: 'Prenotazione eliminata con successo.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prenotation
      @prenotation = Prenotation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prenotation_params
      params.require(:prenotation).permit(:name, :start_time, :end_time)
    end
end

app/helpers/prenotations_helper.rb
module PrenotationsHelper
end

app/views/prenotations/_form.html.erb
<%= form_for([@property, @property.prenotations.build], html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @prenotation.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@prenotation.errors.count, "error") %> prohibited this prenotation from being saved:</h4>

      <ul>
      <% @prenotation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">

      <%= f.label :nome, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :name, class: "form-control" %>
      </div>

  </div>
  
  <div class="form-group">

      <%= f.label :inizio, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.datetime_select :start_time, class: "form-control" %>
      </div>

  </div>
  <div class="form-group">

      <%= f.label :fine, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.datetime_select :end_time, class: "form-control" %>
      </div>

  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit value: "Crea prenotazione", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/prenotations/index.html.erb
<h3> Prenotazioni attive per: <%= @property.title %></h3>

<br>
<%= link_to "Torna alla proprietà", property_path(@property), class: 'btn btn-default' %>
<br><br>
<%= link_to new_property_prenotation_path(@property), class: 'btn btn-primary' do %>
  <span class="glyphicon glyphicon-plus"></span>
  Nuova prenotazione
<% end %>
<br><br>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Start time</th>
            <th>End time</th>
        <th>Opzioni</th>
      </tr>
    </thead>

    <tbody>
      <% @prenotations.each do |prenotation| %>
        <%= content_tag :tr, id: dom_id(prenotation), class: dom_class(prenotation) do %>
                      <td><%= prenotation.name %></td>
                      <td><%= prenotation.start_time %></td>
                      <td><%= prenotation.end_time %></td>
          <td><%= link_to 'Elimina', [@property, prenotation], method: :delete, data: { confirm: 'Sei sicuro?' }, :class => 'btn btn-danger' %></td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/prenotations/new.html.erb
<div class="page-header">
  <%= link_to property_prenotations_path(@property), class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Indietro
  <% end %>
  <h1>Nuova prenotazione</h1>
</div>

<%= render 'form' %>