config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/profile'
  get 'welcome/results'
  get 'welcome/favourites'
  get 'welcome/following'

  post 'properties/:id/add_to_f', to: 'properties#add_to_f', as: 'add_to_f_property'
  post 'properties/:id/remove_from_f', to: 'properties#remove_from_f', as: 'remove_from_f_property'

  post 'properties/:id/follow', to: 'properties#follow', as: 'follow'
  post 'properties/:id/unfollow', to: 'properties#unfollow', as: 'unfollow'


  get 'properties/:id/summary', to: 'properties#summary', as: 'summary'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"
  resources :properties do
    resources :prenotations

    resources :questions do
      resources :answers
    end
    
    resources :reviews
  end

  resources :conversations do
    resources :messages
  end
  resources :ratings
  resources :answer_ratings
  resources :reviews
  resources :questions
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
  
  has_many :answer_rating
end

app/models/answer_rating.rb
class AnswerRating < ApplicationRecord
  belongs_to :user
  belongs_to :answer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/prenotation.rb
class Prenotation < ApplicationRecord
  belongs_to :property
end

app/models/property.rb
class Property < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5, maximum: 50}
  validates :description, presence:true, length: { minimum: 10}
  validates :price, presence:true, numericality: {greater_than: 0}
  validates :city, presence: true

  belongs_to :user
  has_and_belongs_to_many :favouriters, class_name: "User", join_table: "favouriters_and_favourites"
  paginates_per 3

  serialize :categories, Array

  has_attached_file :img1, styles: { small: "200x200>", medium: "300x300>", thumb: "100x100>" }, default_url: ":style/default_local.jpg"
  validates_attachment_content_type :img1, content_type: /\Aimage\/.*\z/

  has_attached_file :img2, styles: { small: "200x200>", medium: "300x300>", thumb: "100x100>" }, default_url: ":style/default_local.jpg"
  validates_attachment_content_type :img2, content_type: /\Aimage\/.*\z/

  has_attached_file :img3, styles: { small: "200x200>", medium: "300x300>", thumb: "100x100>" }, default_url: ":style/default_local.jpg"
  validates_attachment_content_type :img3, content_type: /\Aimage\/.*\z/

  has_many :questions, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :prenotations, dependent: :destroy

  geocoded_by :city
  after_validation :geocode
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :property

  has_many :answers, dependent: :destroy
  has_many :ratings, dependent: :destroy

  validates :body, presence: true, length: {minimum: 5}
  validates :valutation, numericality: {only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5}
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :property
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true
  validates :valutation, presence: true, numericality: {only_integer: true, greater_than: 0, less_than_or_equal_to: 5}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  acts_as_messageable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :properties, dependent: :destroy
  has_many :questions, dependent: :destroy

  has_many :answers, dependent: :destroy

  has_many :reviews, dependent: :destroy

  has_many :ratings
  has_many :answer_rating

  has_and_belongs_to_many :favourites, class_name: "Property", join_table: "favouriters_and_favourites"

  has_and_belongs_to_many(:followings,
    class_name: "User",
    :join_table => "following_connections",
    :foreign_key => "follower_id",
    :association_foreign_key => "following_id")

  validates :username, uniqueness: true, presence: true

  has_attached_file :avatar, styles: { small: "200x200>", medium: "300x300>", thumb: "100x100>" }, default_url: ":style/default_user.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.username = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end

  def mailboxer_email(object)
    nil
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.create(answer_params)
    @answer.update_attribute(:valutation, 0)
    current_user.answers << @answer
    redirect_to property_question_path(@question, @question.property)
  end

  def destroy
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
    @answer.destroy
    redirect_to property_question_path(@question, @question.property)
  end

  private
    def answer_params
      params.require(:answer).permit(:body,:valutation)
    end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
    def create
      @question = Question.find(params[:rating][:question_id])
      @rating = @question.ratings.create(rating_params)
      rating_num = @question.ratings.count();
      if rating_num > 0
        val_media = @question.ratings.sum(:stars) / rating_num
      else
        val_media = @rating.stars
      end
      @question.update_attribute(:valutation, val_media)
      current_user.ratings << @rating
      redirect_back(fallback_location: root_path)
    end
    
    def update
      rating = Rating.find(params[:id])
      if (rating.user_id != current_user.id)
        create
      else
        rating.update_attribute(:stars, params[:rating][:stars])
      end
      question = Question.find(rating.question_id)
      val_media = question.ratings.sum(:stars) / question.ratings.count()
      question.update_attribute(:valutation, val_media)
    end
    
    private
      def rating_params
        params.require(:rating).permit(:stars)
      end
end

app/helpers/answer_ratings_helper.rb
module AnswerRatingsHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prenotations_helper.rb
module PrenotationsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Ωmega</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Ω", welcome_index_path , class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li><%= link_to "Profilo", welcome_profile_path %></li>
            <li><%= link_to "Mie inserzioni", properties_path %></li>
            <li><%= link_to "Preferiti", welcome_favourites_path %></li>
            <li><%= link_to "Following", welcome_following_path %></li>
            <li>
              <%= link_to conversations_path, class: "btn btn-default btn-lg btn-link" do %>
                <i class="glyphicon glyphicon-comment ">
                </i>
              <% end %>
              <% if current_user.unread_inbox_count != 0 %>
                <span class="badge badge-notify small" >
                  <%= current_user.unread_inbox_count %>
                </span>

              <% end %>
            </li>
            <li><%= link_to "Esci", destroy_user_session_path, method: :delete %></li>


          <% else %>

            <li><%= link_to "Accedi", new_user_session_path %></li>
            <li><%= link_to "Registrati",  new_user_registration_path %></li>
          <% end %>

        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>
  </div>

  <div class="container">
    <%= yield %>
  </div>
  <hr />

  <div id="contact">
      <a href="mailto:dabbraccio.francesco@gmail.com" >Contattaci</a>
  </div>

</body>
</html>